config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :user_steps
  post '/user_steps/seeking' => 'user_steps#update'

  get '/signup' => 'users#new', as: 'new_user'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show', as: 'user'
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy'
  post '/sessions' => 'sessions#create', as: 'create_session'
  get '/users/:id/edit' => 'users#edit', as: 'edit_user'
  get '/users/:id/video' => 'start_matches#video', as: 'user_video'
  get '/users/:id/answers' => 'start_matches#answers', as: 'user_answers'
  get '/users/:id/playlist' => 'start_matches#playlist', as: 'user_playlist'
  get '/users/:id/matches' =>'start_matches#matches', as: 'user_matches'
  get '/users/:id/next_match' => 'start_matches#next_match', as: 'next_match'
  get '/users/:id/profile' => 'start_matches#profile', as: 'user_profile'
  patch '/users/:id' => 'users#update'
  get '/users/:id/no_more' => 'start_matches#no_more', as: 'no_users'

  get "*unmatched_route", to: "application#not_found", as: 'error'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  cattr_accessor :current_user
  #attr_accessible :link

  SEEKING = ['f4f', 'f4m', 'm4f', 'm4m']

    def self.confirm(params)
      @user = User.where("email ILIKE ?", params[:email]).first
      @user.try(:authenticate, params[:password])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def not_found
  render :file => "public/404"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Successfully logged in."
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Incorrect email or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end

private

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/start_matches_controller.rb
class StartMatchesController < ApplicationController

@@potential_matches = []
@@next_match

before_action :find_user, only: [:video, :answers, :playlist, :profile]

  def matches
    # get an array of compatible matches
    @user = current_user
    seeking = current_user.seeking
    matches = @@potential_matches
    if seeking == 'f4m'
      matches = User.where(seeking: 'm4f')
    elsif seeking == 'm4f'
      matches = User.where(seeking: 'f4m')
    elsif seeking == 'm4m'
      matches = User.where(seeking: 'm4m')
    else
      matches = User.where(seeking: 'f4f')
    end

    # make this array an array of corresponding user ids
    matches.each do |match|
      if match.id != current_user.id
        @@potential_matches.push(match.id)
      end
    end

    # send the first matched user
    next_id = @@potential_matches.shift
    @next_match = User.find(next_id)
    redirect_to next_match_path
  end

  def next_match
    # the next match for the current_user to look at
    next_id = @@potential_matches.shift
    # this will be the user
    @@next_match = User.find(next_id)
    if @@potential_matches.length == 0
      flash[:notice] = "This is your last potential match. Come back later or maybe lower your standards."
    end
    redirect_to user_video_path and return
  end

  def video
  end

  def answers
  end

  def playlist
  end

  def profile
    flash[:notice] = "Here is your match! Feel free to keep matching"
  end

private

  def find_user
    @user = @@next_match
  end

end

app/controllers/user_steps_controller.rb
class UserStepsController < ApplicationController
  include Wicked::Wizard
  steps :seeking, :video, :answers, :playlist

  def show
    @user = current_user
    render_wizard
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    render_wizard @user
  end

  def finish_wizard_path
    user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :seeking, :age, :profile_video, :answer1, :answer2, :answer3, :answer4, :answer5, :answer6, :answer7, :playlist, :suitors, :location, :profile_photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include AuthHelper

  before_action :logged_in?, except: [:index, :new, :create]
  before_action :find_user, only: [:show, :edit, :update, :video, :answers, :playlist]

  def index
    @user = User.new
  end

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:notice] = "Congratulations, you have successfully signed up!"
      redirect_to user_steps_path
    else
      flash[:notice] = "Sorry, please try again.There are some issues:  #{@user.errors.full_messages.join(', ')}."
      redirect_to new_user_path
    end
  end

  def edit
    if !auth_through_user
      auth_fail("Uh Uh Uh", user_path)
    end
  end

  def update
    if auth_through_user
      if @user.update(user_params)
        flash[:notice] = "Your profile was successfully updated."
        redirect_to user_path
      else
        redirect_to user_path
      end
    else
      auth_fail("uh uh uh", user_path)
    end
  end

  def video
    seeking = current_user.seeking
    matches = @potential_matches
    if seeking == 'f4m'
      matches = User.where(seeking: 'm4f')
    elsif seeking == 'm4f'
      matches = User.where(seeking: 'f4m')
    elsif seeking == 'm4m'
      matches = User.where(seeking: 'm4m')
    else
      matches = User.where(seeking: 'f4f')
    end
    matches.each do |match|
      if match.id != @user.id
        current_user.suitors.push(match.id)
      end
    end
    #flash.now[:notice] = "Here is your potential matches profile video, proceed to judge them by it."
  end

  def answers
    #flash.now[:notice] = "Here is your potential matches answers, please continue the judging."
  end

  def playlist
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :profile_photo)
  end

  def find_user
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
  def auth_through_user
    current_user != nil && current_user.id == @user.id
  end

  def auth_fail(reason, redirect_path)
    flash[:notice] = reason
    flash[:bruh] = true
    redirect_to redirect_path
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      flash[:notice] = "You must be logged in to view that."
      redirect_to login_path
    end
  end

  def logged_in
    unless logged_in?
      redirect_to login_path
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/start_matches_helper.rb
module StartMatchesHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicLovers</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="icon" href="http://i.imgur.com/LJ7HS6Z.png">
    <script>
      UPLOADCARE_LOCALE = "en";
      UPLOADCARE_TABS = "file url facebook gdrive dropbox instagram evernote flickr skydrive";
      UPLOADCARE_PUBLIC_KEY = "5dd77238e4a69090c9c9";
    </script>
    <script charset="utf-8" src="//ucarecdn.com/widget/2.10.0/uploadcare/uploadcare.full.min.js"></script>
  </head>

  <body>
    <% if current_user %>
    <nav>
     <div class="nav-wrapper nav-color lighten-7">
       <img class="nav-logo logo" src="http://i.imgur.com/LJ7HS6Z.png"/>
       <a href="#" data-activates="mobile-demo" class="button-collapse hamburger" id='mobile-hamburger'><i class="material-icons">menu</i></a>
       <ul class="right hide-on-med-and-down">
         <% if current_user %>
           <li><span><%= link_to "Profile", current_user, :class => 'nav-hover' %></span></li>
           <li><%= link_to "Logout", "/logout", :class => 'nav-hover' %></li>
         <% else %>
           <li><%= link_to 'Login', login_path, :class => 'nav-hover' %></li>
           <li><%= link_to 'Signup', new_user_path, :class => 'nav-hover' %></li>
         <% end %>
       </ul>
       <ul class="side-nav" id="mobile-demo">
         <div class="slide-bar">
           <% if current_user %>
             <li><span><%= link_to "Profile", current_user, :class => 'nav-hover' %></span></li>
             <li><%= link_to "Logout", "/logout" %></li>
           <% else %>
             <li><%= link_to 'Login', login_path %></li>
             <li><%= link_to 'Signup', new_user_path %></li>
           <% end %>

       </div>
       </ul>
     </div>
    </nav>
    <% end %>
    <%= yield %>
    <% if notice %>
      <% if flash[:bruh] %>
       <script type="text/javascript">
         Materialize.toast('<%= notice %>', 6000, 'bruh')
       </script>
      <% else %>
       <script type="text/javascript">
         Materialize.toast('<%= notice %>', 6000)
       </script>
      <% end %>
     <% end %>
  </body>
</html>

app/views/start_matches/answers.html.erb
<div class="user-answers">
  <h3 class="mobile-show-title"> Answers from -<%= @user.username %> </h3>
  <h5> Question #1 </h5>
    <p><b>Tomorrow is Saturday would you rather be at a musc festival, see a show at a sold out arena, get tickets for a great local venue, go down the street to a house show or stay at home and listen to your favorite album?</b></p>
    <%= @user.answer1 %>
  <h5> Question #2 </h5>
    <p><b>Fu@k, Marry, Kill? Justin Beiber, Drake, Justin Timberlake</b></p>
    <%= @user.answer2 %>
  <h5> Question #3 </h5>
    <p><b>What is the first concert that you chose to go to and how old were you?</b></p>
    <%= @user.answer3 %>
  <h5> Question #4 </h5>
    <p><b>What is the first album that you bought for yourself?</b></p>
    <%= @user.answer4 %>
  <h5> Question #5 </h5>
    <p><b>You are in charge of booking for Coachella next year and you can resurrect the dead. Who are your three headliners?</b></p>
    <%= @user.answer5 %>
  <h5> Question #6 </h5>
    <p><b>Fu@k, Marry, Kill? Rhianna, Beyonce, Taylor Swift</b></p>
    <%= @user.answer6 %>
  <h5> Question #7 </h5>
    <p><b>If you were in a band would you rather be the singer, songwriter, or play an instrument?</b></p>
    <%= @user.answer7%>
</div>
<div class="answers-icons" id="playlist-icons">
  <span class="answers-thumbdown">
    <%= link_to next_match_path do %>
      <i class="large material-icons">thumb_down</i>
    <% end %>
  </span>
    <span class="answers-thumbup">
      <%= link_to user_playlist_path do %>
        <i class="large material-icons">thumb_up</i>
      <% end %>
  </span>
</div>
<div id ="footer">
  <div class="playlist-icons">
    <span class="thumbdown">
      <%= link_to next_match_path do %>
        <i class="large material-icons">thumb_down</i>
      <% end %>
    </span>
    <span class="thumbup">
      <%= link_to user_playlist_path do %>
        <i class="large material-icons">thumb_up</i>
      <% end %>
    </span>
  </div>
</div>

app/views/start_matches/matches.html.erb
<div class='start_matches'>
  <h5 class='mobile-show-title'>Here is your first match. Click below to view their video. If at any point you do not like their content click the thumbs down to move on.</h5>
  <%= link_to "see video", next_match_path, :class => 'btn' %>
</div>

app/views/start_matches/next_match.html.erb
  <%= link_to "video", user_video_path %> 

app/views/start_matches/playlist.html.erb
<h3 class="mobile-show-title"> Playlist from -<%= @user.username %> </h3>
<div class="playlist-show">
  <div class="playlistWrapper">
    <iframe src="https://embed.spotify.com/?uri=<%= @user.playlist %>" width="740" height="400" frameborder="0" allowtransparency="true"></iframe>
  </div>
</div>
<div class="playlist-icons" id="playlist-icons">
  <span class="playlist-thumbdown">
    <%= link_to next_match_path do %>
      <i class="large material-icons">thumb_down</i>
    <% end %>
  </span>
  <span class="playlist-thumbup">
    <%= link_to user_profile_path do %>
      <i class="large material-icons">thumb_up</i>
    <% end %>
  </span>
</div>
<div id ="footer">
  <div class="playlist-icons">
    <span class="thumbdown">
      <%= link_to next_match_path do %>
        <i class="large material-icons">thumb_down</i>
      <% end %>
    </span>
    <span class="thumbup">
      <%= link_to user_profile_path do %>
        <i class="large material-icons">thumb_up</i>
      <% end %>
    </span>
  </div>
</div>

app/views/start_matches/profile.html.erb
<div class="profile">
  <h3 id="mobile-name"><%= @user.first_name %> <%= @user.last_name %></h3>
  <div class='profile-photo'>
  <img src='<%= @user.profile_photo %>' class='profile-photo' id="mobile-profile"><br>
  <span class='age'><%= @user.age %></span>
  </div>
  <div class="profile-location">
  <h5 id="mobile-location"> Lives in </h5>
  <%= @user.location %>
  </div>
  <div class="mobile-edit-button">
  <% if current_user != nil && current_user.id == @user.id %>
    <%= link_to "Edit Profile", edit_user_path, :class => "btn mobile-edit"  %> <br><br>
    <%= link_to "Start Matching", user_matches_path, :class => "btn mobile-edit" %>
  <% end %>
  </div>
    <%= link_to "Keep Matching", next_match_path, :class => "btn mobile-edit" %>
</div>

app/views/start_matches/video.html.erb
<h3 class="mobile-show-title"> Video for -<%= @user.username %> </h3>
<div class="video-show">
  <div class="videoWrapper">
    <iframe width="740" height="416" src="https://www.youtube.com/embed/<%= @user.profile_video %>" frameborder="0" allowfullscreen></iframe>
  </div>
</div>
<div class="video-icons" id="playlist-icons">
  <span class="video-thumbdown">
    <%= link_to next_match_path do %>
      <i class="large material-icons">thumb_down</i>
    <% end %>
  </span>
  <span class="video-thumbup">
    <%= link_to user_answers_path do %>
      <i class="large material-icons">thumb_up</i>
    <% end %>
  </span>
</div>
<div id ="footer">
  <div class="playlist-icons">
    <span class="thumbdown">
      <%= link_to next_match_path do %>
        <i class="large material-icons">thumb_down</i>
      <% end %>
    </span>
    <span class="thumbup">
      <%= link_to user_answers_path do %>
        <i class="large material-icons">thumb_up</i>
      <% end %>
    </span>
  </div>
</div>

app/views/user_steps/answers.html.erb
<div class='qanda'>
  <div class='answers-top'>
    <h5 class='mobile-show-title'> Great! You're on your way. Now its time to get a little more personal. Answer these 7 questions to the best of your ability, get creative with your answers and explain your choices. Click continue when you are satisfied with your responses.</h5>
  </div>
  <%= form_for @user, url: wizard_path  do |f| %>
    <h5> Question #1 </h5>
      <p>Tomorrow is Saturday would you rather be at a musc festival, see a show at a sold out arena, get tickets for a great local venue, go down the street to a house show or stay at home and listen to your favorite album?</p>
      <%= f.text_area :answer1, :placeholder => 'Answer Here' %>
    <h5> Question #2 </h5>
      <p>Fu@k, Marry, Kill? Justin Beiber, Drake, Justin Timberlake</p>
      <%= f.text_area :answer2, :placeholder => 'Answer Here' %>
    <h5> Question #3 </h5>
      <p>What is the first concert that you chose to go to and how old were you?</p>
      <%= f.text_area :answer3, :placeholder => 'Answer Here' %>
    <h5> Question #4 </h5>
      <p>What is the first album that you bought for yourself?</p>
      <%= f.text_area :answer4, :placeholder => 'Answer Here' %>
    <h5> Question #5 </h5>
      <p>You are in charge of booking for Coachella next year and you can resurrect the dead. Who are your three headliners?</p>
      <%= f.text_area :answer5, :placeholder => 'Answer Here' %>
    <h5> Question #6 </h5>
      <p>Fu@k, Marry, Kill? Rhianna, Beyonce, Taylor Swift</p>
      <%= f.text_area :answer6, :placeholder => 'Answer Here' %>
    <h5> Question #7 </h5>
      <p>If you were in a band would you rather be the singer, songwriter, or play an instrument?</p>
      <%= f.text_area :answer7, :placeholder => 'Answer Here' %>
      <%= f.submit "Sumbit", :class=>'waves-effect waves-red waves-ripple btn' %>
  <% end %>
</body>

app/views/user_steps/playlist.html.erb
<h5 class='mobile-show-title'>Here is where things get a bit trickier, stick with it and you will be finding matches in no time. At this point you are going to make a 10 track playlist on Spotify and paste a link to its URI on this page. Click the example below if you have never done this before. Studies that I have just made up show that music preferences are the number one factor of compatability in a relationship.</h5>
<div class="mobile-spotify">
  <a href="https://support.spotify.com/us/using_spotify/playlists/save-your-music-with-playlists/"><img class="mobile-spotify" src='http://i.imgur.com/g2lE0kX.png'></a>
</div>
<%= form_for @user, url: wizard_path  do |f| %>
  <%= f.text_field :playlist, :placeholder=>"URI here" %>
  <%= f.submit "Submit", :class=>'waves-effect waves-red waves-ripple btn' %>
<% end %>

app/views/user_steps/seeking.html.erb
<h5> Welcome <%= @user.first_name %>, tell us a bit about yourself. </h5>
<div class="edit-form input-field">
  <%= form_for @user, url: wizard_path  do |f| %>
    <span class="signup-age">I am   <%= f.number_field :age, :placeholder=>" Age", style: 'display:inline; width: 44px;'%> years old</span> <br>
    <span class="signup-location">living in  <%= f.text_field :location, :placeholder=>"  City", style: 'display:inline; width: 120px;' %></span><br>
    <span class="seeking">looking for<%= f.collection_select :seeking, User::SEEKING, :to_s, :to_s, :include_blank => false, :prompt => 'Select'%><br>
    <%= f.submit "Submit", :class=>'waves-effect waves-red waves-ripple btn' %>
  <% end %>
</div>

app/views/user_steps/video.html.erb
<h5 class='mobile-show-title'>Time to show potential matches who you are... and what better way than your favorite youtube video. This will serve as your "profile video" and will be the first thing a potential match will see and base their judgements off of, so no pressure. Choose something that represesnts your music taste, sense of humor or even an hour long Python lecture. It is completely up to you to decide how you want to make your first impression. Grab the end of the link like this <span><img class="youtube" src="http://i.imgur.com/kSM39R9.png"> and paste it below. Click continue when you're done.</h5>

<%= form_for @user, url: wizard_path  do |f| %>
  <%= f.text_field :profile_video, :placeholder => 'Youtube URL here, ex. dQw4w9WgXcQ' %>
    <%= f.submit "Upload", :class=>'waves-effect waves-red waves-ripple btn' %>
<% end %>

<div class="video-show" id="mobile-hide">
  <div class="videoWrapper">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ"frameborder="0" allowfullscreen></iframe>
  </div>
</div>

app/views/users/answers.html.erb
<div class="user-answers">
  <h3 class="mobile-show-title"> Answers from -<%= @user.username %> </h3>
  <h5> Question #1 </h5>
    <p><b>Tomorrow is Saturday would you rather be at a musc festival, see a show at a sold out arena, get tickets for a great local venue, go down the street to a house show or stay at home and listen to your favorite album?</b></p>
    <%= @user.answer1 %>
  <h5> Question #2 </h5>
    <p><b>Fu@k, Marry, Kill? Justin Beiber, Drake, Justin Timberlake</b></p>
    <%= @user.answer2 %>
  <h5> Question #3 </h5>
    <p><b>What is the first concert that you chose to go to and how old were you?</b></p>
    <%= @user.answer3 %>
  <h5> Question #4 </h5>
    <p><b>What is the first album that you bought for yourself?</b></p>
    <%= @user.answer4 %>
  <h5> Question #5 </h5>
    <p><b>You are in charge of booking for Coachella next year and you can resurrect the dead. Who are your three headliners?</b></p>
    <%= @user.answer5 %>
  <h5> Question #6 </h5>
    <p><b>Fu@k, Marry, Kill? Rhianna, Beyonce, Taylor Swift</b></p>
    <%= @user.answer6 %>
  <h5> Question #7 </h5>
    <p><b>If you were in a band would you rather be the singer, songwriter, or play an instrument?</b></p>
    <%= @user.answer7%>
</div>
<div class="answers-icons">
  <span class="answers-thumbdown">
    <%= link_to user_answers_path do %>
      <i class="large material-icons">thumb_down</i>
    <% end %>
  </span>
    <span class="answers-thumbup">
      <%= link_to user_playlist_path do %>
        <i class="large material-icons">thumb_up</i>
      <% end %>
  </span>
</div>

app/views/users/edit.html.erb
<div class = "edit-profile">
  <%= form_for @user do |f| %>
    First Name: <%= f.text_field :first_name, :placeholder=>"First Name", :class => 'inputbox'%>
    Last Name: <%= f.text_field :last_name, :placeholder=>"Last Name", :class => 'inputbox' %>
    Username: <%= f.text_field :username, :placeholder=>"User Name", :class => 'inputbox' %>
    Email:<%= f.text_field :email, :placeholder=>"Email", :class => 'inputbox' %>
    Age:<%= f.number_field :age, :placeholder=>"Age", style: 'display:inline;'%>
    Location:<%= f.text_field :location, :placeholder=>"City", :class => 'inputbox' %>
    Provile Video:<%= f.text_field :profile_video, :placeholder => 'Youtube URL here, ex. dQw4w9WgXcQ', :class => 'inputbox' %>
    Spotify Playlist:<%= f.text_field :playlist, :placeholder=>"URI here", :class => 'inputbox' %>
    Seeking: <%= f.collection_select :seeking, User::SEEKING, :to_s, :to_s, :include_blank => false, :prompt => 'Select', :class => 'inputbox' %>
    <h5> Question #1 </h5>
    <p></b>Tomorrow is Saturday would you rather be at a musc festival, see a show at a sold out arena, get tickets for a great local venue, go down the street to a house show or stay at home and listen to your favorite album?</b></p>
      <%= f.text_area :answer1, :placeholder => 'Answer Here', :class => 'inputbox' %>
    <h5> Question #2 </h5>
    <p></b>Fu@k, Marry, Kill? Justin Beiber, Drake, Justin Timberlake</b></p>
      <%= f.text_area :answer2, :placeholder => 'Answer Here', :class => 'inputbox' %>
    <h5> Question #3 </h5>
    <p></b>What is the first concert that you chose to go to and how old were you?</b></p>
      <%= f.text_area :answer3, :placeholder => 'Answer Here', :class => 'inputbox' %>
    <h5> Question #4 </h5>
    <p></b>What is the first album that you bought for yourself?</b></p>
      <%= f.text_area :answer4, :placeholder => 'Answer Here', :class => 'inputbox' %>
    <h5> Question #5 </h5>
    <p></b>You are in charge of booking for Coachella next year and you can resurrect the dead. Who are your three headliners?</b></p>
      <%= f.text_area :answer5, :placeholder => 'Answer Here', :class => 'inputbox' %>
    <h5> Question #6 </h5>
    <p></b>Fu@k, Marry, Kill? Rhianna, Beyonce, Taylor Swift</b></p>
      <%= f.text_area :answer6, :placeholder => 'Answer Here', :class => 'inputbox' %>
    <h5> Question #7 </h5>
    <p></b>If you were in a band would you rather be the singer, songwriter, or play an instrument?</b></p>
      <%= f.text_area :answer7, :placeholder => 'Answer Here', :class => 'inputbox' %>
    Profile Photo:<br><%= f.uploadcare_uploader :profile_photo, :data => {:images_only => true, :crop => "500x500 minimum", :image_shrink => "500x500", :clearable => true }, :class => 'inputbox' %><br><br>
    <%= f.submit "Submit", :class=>'waves-effect waves-red waves-ripple btn' %><br>
  <% end %>
</div>

app/views/users/index.html.erb
<body class="musiclovers-background">
  <img class='responsive-img img-title' src='http://i.imgur.com/XQaeuym.png'>

  <h6 class='splash-text'> Music Lovers is a dating app for singles that are looking to meet others with a similar music taste. Click below to start.</h6>

  <%= link_to 'Get Started', new_user_path, :class => 'btn splashbtn' %>
</body>

app/views/users/playlist.html.erb
<h3 class="mobile-show-title"> Playlist from -<%= @user.username %> </h3>
<div class="playlist-show">
  <div class="playlistWrapper">
    <iframe src="https://embed.spotify.com/?uri=<%= @user.playlist %>" width="740" height="400" frameborder="0" allowtransparency="true"></iframe>
  </div>
  <div class="playlist-icons"
    <span class="video-thumbdown">
      <%= link_to user_answers_path do %>
        <i class="large material-icons">thumb_down</i>
      <% end %>
    </span>
      <span class="video-thumbup">
        <%= link_to user_answers_path do %>
          <i class="large material-icons">thumb_up</i>
        <% end %>
    </span>
  </div>
  </div>
<div>

app/views/users/show.html.erb
<% if current_user != nil && current_user.id == @user.id %>
<div class="profile">
  <h3 id="mobile-name"><%= @user.first_name %> <%= @user.last_name %></h3>
  <div class='profile-photo'>
  <img src='<%= @user.profile_photo %>' class='profile-photo' id="mobile-profile"><br>
  <span class='age'><%= @user.age %></span>
  </div>
  <div class="profile-location">
  <h5 id="mobile-location"> Lives in </h5>
  <%= @user.location %>
  </div>
  <div class="mobile-edit-button">

    <%= link_to "Edit Profile", edit_user_path, :class => "btn mobile-edit"  %> <br><br>
    <%= link_to "Start Matching", user_matches_path, :class => "btn mobile-edit" %>

  </div>
</div>
<% else %>
  <% flash[:notice] = "You must go through the screening process to view this profile." %>
<% end %>

app/views/users/video.html.erb
<h3 class="mobile-show-title"> Video for -<%= @user.username %> </h3>
<div class="video-show">
  <div class="videoWrapper">
    <iframe width="740" height="416" src="https://www.youtube.com/embed/<%= @user.profile_video %>" frameborder="0" allowfullscreen></iframe>
  </div>
</div>
<div class="video-icons">
  <span class="video-thumbdown">
    <%= link_to user_answers_path do %>
      <i class="large material-icons">thumb_down</i>
    <% end %>
  </span>
  <span class="video-thumbup">
    <%= link_to user_answers_path do %>
      <i class="large material-icons">thumb_up</i>
    <% end %>
  </span>
</div>